export const GET_FILES_REQUEST='GET_FILES_REQUEST';
export const GET_FILES_SUCCESS='GET_FILES_SUCCESS';
export const GET_FILES_FAIL='GET_FILES_FAIL';

export const UPLOAD_FILE_REQUEST='UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS='UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAIL='UPLOAD_FILE_FAIL';